# ---
# jupyter:
#   jupytext:
#     cell_metadata_filter: tags,-all
#     formats: py:percent,ipynb
#     notebook_metadata_filter: -jupytext.text_representation.jupytext_version
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Introduction to running PROCESS
#
# %% [markdown]
# A Jupyter notebook to demonstrate usage of the `process` package.
#

# %% [markdown]
# <div class="alert alert-block alert-info">
# <b>NOTE</b> We run the examples in a temporary directory so all the inputs are copied there and the outputs contained there before the directory is removed when the example has finished running. This keeps the examples directory tidy and does not permanently modify any data files. The use of temporary directories is not needed for regular use of PROCESS.
# </div>

# %% [markdown]
# Process can be run from the command line with the `process` command or as a standard python package.
# Using process as a package allows for more complex scripting of a process run for different tasks.


# %% [markdown]
# ## Basic run of Process
# Run Process on an input file using the `SingleRun` class. This outputs an `MFILE.DAT` and an `OUT.DAT`.
#
# This is equivalent to running `process -i data/large_tokamak_IN.DAT` in the examples folder.

# %%
# %load_ext autoreload
# %autoreload 2

import shutil
import tempfile
from pathlib import Path

from process.core.repository import get_process_root
from process.main import SingleRun

# Define input file name relative to project dir, then copy to temp dir
data_dir = get_process_root() / "../examples/data/"
input_file = data_dir / "large_tokamak_IN.DAT"

# Copy the file to avoid polluting the project directory with example files
temp_dir = tempfile.TemporaryDirectory()
input_path = Path(temp_dir.name) / "large_tokamak_IN.DAT"
shutil.copy(input_file, input_path)

# Run process on an input file in a temporary directory
single_run = SingleRun(input_path.as_posix())
single_run.run()

# %% [markdown]
# ## Plot summary
# Create a summary of the generated `MFILE.DAT` using `plot_summary`.
#
# You can also call `plot_summary` from the cli with `process plot summary`

# %%
from process.core.io.plot import plot_summary

# Pdf and png output are also available
plot_summary(single_run.mfile_path, output_format="none", show=True)

# %% [markdown]
# ## View key output variables
# Using the `MFILE` we generated by running the large tokamak scenario above,
# we have set some values on the `CostModel` instance and can print them.

# %%

# Print some values on the CostModel instance
print(f"Heat transport system: {single_run.data.costs.c226:.3e} M$")
print(f"Electrical plant equipment: {single_run.data.costs.c24:.3e} M$")

# %%
# Clean up
temp_dir.cleanup()
