"""Provides the classes to find, download, and access tracked MFiles on
a remote data repository.
"""

import dataclasses
import logging
import re
import subprocess
from pathlib import Path

from platformdirs import user_cache_path

logger = logging.getLogger(__name__)

TEST_ASSET_CACHE_DIR = user_cache_path("PROCESS-regression-tests", "ukaea")


@dataclasses.dataclass
class TrackedMFile:
    hash: str
    scenario_name: str
    location: Path


class RegressionTestAssetCollector:
    def __init__(self):
        self._hashes = self._git_commit_hashes()
        self._repo_dir = self._get_regression_assets()
        self._tracked_mfiles = self._get_tracked_mfiles()

    def _get_regression_assets(self):
        """Ensures the user has an up-to-date local copy of the regression references by cloning/pulling
        the remote repository to a local cache.
        """
        repo_dir = TEST_ASSET_CACHE_DIR / "process-tracking-data"
        if not repo_dir.exists():
            repo_dir.mkdir(parents=True)

            subprocess.run(
                f"git clone https://github.com/timothy-nunn/process-tracking-data.git '{repo_dir.as_posix()}'",
                shell=True,
                check=True,
            )
        else:
            subprocess.run(
                "git pull", shell=True, check=True, cwd=repo_dir, capture_output=True
            )

        return repo_dir

    def get_reference_mfile(self, scenario_name: str, target_hash: str | None = None):
        """Finds the most recent reference MFile for `<scenario_name>.IN.DAT`
        and downloads it to the `directory` with the name `ref.<scenario_name>.MFILE.DAT`.

        Providing a `target_hash` will ONLY return a reference MFILE that exactly
        matches the requested commit hash.

        :param scenario_name: the reference MFile to be found was generated by running
        <scenario_name>.IN.DAT.
        :type scenario_name: str
        :param directory: the directory to download the reference MFile to
        :type directory: Path
        :param target_hash: if provided, only a reference MFile tracked for this commit
        will be downloaded, if available.
        :type target_hash:

        :returns: Path to the downloaded reference MFile, if no reference MFile can be found,
        `None` is returned.
        :rtype: Path
        """

        for mf in self._tracked_mfiles:
            if (mf.scenario_name == scenario_name and target_hash is None) or (
                mf.scenario_name == scenario_name and target_hash == mf.hash
            ):
                return mf.location

        return None

    def _git_commit_hashes(self):
        """Returns the list of commit hashes.

        :returns: a list of commit hashes from 'git log'
        :rtype: list[str]
        """
        return (
            subprocess.run(
                'git log --format="%H"',
                shell=True,
                capture_output=True,
                check=True,
            )
            .stdout.decode()
            .split("\n")
        )

    def _get_tracked_mfiles(self):
        """Gets a list of tracked MFiles.

        :returns: a list of tracked MFiles sorted to match the order of
        hashes returned from `_git_commit_hashes`.
        :rtype: list[TrackedMFile]
        """
        # create a list of tracked MFiles from the list of all files
        # in the repository.
        # Only keep TrackedMFiles that are tracked for a commit on the
        # current branch. This stops issues arising from main being
        # ahead of the feature branch and having newer tracks.
        tracked_mfiles = [
            mfile
            for f in self._repo_dir.glob("*.DAT")
            if (mfile := self._get_tracked_mfile(f)) is not None
            and mfile.hash in self._hashes
        ]

        # order tracked MFiles to match order of the git log
        return sorted(
            tracked_mfiles,
            key=lambda m: self._hashes.index(m.hash),
        )

    def _get_tracked_mfile(self, file: Path):
        """Converts JSON data of a file tracked on GitHub into a
        `TrackedMFile`, if appropriate

        :param json_data: a dictionary representing a file in the remote repository.
        The dictionary must have fields: 'name' and 'download_url'.
        :type json_data: dict[str, Any]

        :returns: A representation of the tracked MFile, if the file is indeed a
        tracked mfile.
        :rtype: TrackedMFile | None
        """
        rematch = re.match(r"([a-zA-Z0-9_.]+)_MFILE_([a-z0-9]+).DAT", file.name)

        if rematch is None:
            return None
        return TrackedMFile(
            hash=rematch.group(2), scenario_name=rematch.group(1), location=file
        )
