import process.fortran as fortran


def init_process():
    """Routine that calls the initialisation routines
    author: P J Knight, CCFE, Culham Science Centre
    None
    This routine calls the main initialisation routines that set
    the default values for the global variables, reads in data from
    the input file, and checks the run parameters for consistency.
    """
    # Initialise error handling
    fortran.error_handling.initialise_error_list()

    # Initialise the program variables
    initialise_iterative_variables()

    # Initialise the Fortran file specifiers
    # (creating and opening the files in the process)
    fortran.init_module.open_files()

    # Input any desired new initial values
    fortran.process_input.input()

    # Initialise the Stellarator
    fortran.stellarator_module.stinit()

    # Check input data for errors/ambiguities
    fortran.init_module.check()

    fortran.main_module.run_summary()


def init_all_module_vars():
    """Initialise all module variables
    This is vital to ensure a 'clean' state of Process before a new run starts,
    otherwise components of the previous run's state can persist into the new
    run. This matters ever since Process is used as a shared library, rather
    than a 'run-once' executable.
    """
    fortran.numerics.init_numerics()
    fortran.process_input.init_input()
    fortran.buildings_variables.init_buildings_variables()
    fortran.cost_variables.init_cost_variables()
    fortran.divertor_variables.init_divertor_variables()
    fortran.error_handling.init_error_handling()
    fortran.fwbs_variables.init_fwbs_variables()
    fortran.global_variables.init_global_variables()
    fortran.ccfe_hcpb_module.init_ccfe_hcpb_module()
    fortran.heat_transport_variables.init_heat_transport_variables()
    fortran.ife_variables.init_ife_variables()
    fortran.impurity_radiation_module.init_impurity_radiation_module()
    fortran.pfcoil_module.init_pfcoil_module()
    fortran.physics_module.init_physics_module()
    fortran.physics_variables.init_physics_variables()
    fortran.scan_module.init_scan_module()
    fortran.sctfcoil_module.init_sctfcoil_module()
    fortran.stellarator_module.init_stellarator_module()
    fortran.stellarator_variables.init_stellarator_variables()
    fortran.tfcoil_variables.init_tfcoil_variables()
    fortran.times_variables.init_times_variables()
    fortran.constants.init_constants()
    fortran.current_drive_variables.init_current_drive_variables()
    fortran.primary_pumping_variables.init_primary_pumping_variables()
    fortran.pfcoil_variables.init_pfcoil_variables()
    fortran.structure_variables.init_structure_variables()
    fortran.vacuum_variables.init_vacuum_variables()
    fortran.pf_power_variables.init_pf_power_variables()
    fortran.build_variables.init_build_variables()
    fortran.constraint_variables.init_constraint_variables()
    fortran.pulse_variables.init_pulse_variables()
    fortran.rebco_variables.init_rebco_variables()
    fortran.reinke_variables.init_reinke_variables()
    fortran.define_iteration_variables.init_define_iteration_variables()
    fortran.reinke_module.init_reinke_module()
    fortran.water_usage_variables.init_watuse_variables()
    fortran.cs_fatigue_variables.init_cs_fatigue_variables()
    fortran.blanket_library.init_blanket_library()
    fortran.dcll_module.init_dcll_module()

    fortran.init_module.init_fortran_modules()


def initialise_iterative_variables():
    """Initialise each of the iteration variables"""
    fortran.define_iteration_variables.init_itv_1()
    fortran.define_iteration_variables.init_itv_2()
    fortran.define_iteration_variables.init_itv_3()
    fortran.define_iteration_variables.init_itv_4()
    fortran.define_iteration_variables.init_itv_5()
    fortran.define_iteration_variables.init_itv_6()
    fortran.define_iteration_variables.init_itv_7()
    fortran.define_iteration_variables.init_itv_8()
    fortran.define_iteration_variables.init_itv_9()
    fortran.define_iteration_variables.init_itv_10()
    fortran.define_iteration_variables.init_itv_11()
    fortran.define_iteration_variables.init_itv_12()
    fortran.define_iteration_variables.init_itv_13()
    fortran.define_iteration_variables.init_itv_14()
    fortran.define_iteration_variables.init_itv_15()
    fortran.define_iteration_variables.init_itv_16()
    fortran.define_iteration_variables.init_itv_17()
    fortran.define_iteration_variables.init_itv_18()
    fortran.define_iteration_variables.init_itv_19()
    fortran.define_iteration_variables.init_itv_20()
    fortran.define_iteration_variables.init_itv_21()

    fortran.define_iteration_variables.init_itv_23()

    fortran.define_iteration_variables.init_itv_25()
    fortran.define_iteration_variables.init_itv_26()
    fortran.define_iteration_variables.init_itv_27()
    fortran.define_iteration_variables.init_itv_28()
    fortran.define_iteration_variables.init_itv_29()
    fortran.define_iteration_variables.init_itv_30()
    fortran.define_iteration_variables.init_itv_31()
    fortran.define_iteration_variables.init_itv_32()
    fortran.define_iteration_variables.init_itv_33()
    fortran.define_iteration_variables.init_itv_34()
    fortran.define_iteration_variables.init_itv_35()
    fortran.define_iteration_variables.init_itv_36()
    fortran.define_iteration_variables.init_itv_37()
    fortran.define_iteration_variables.init_itv_38()
    fortran.define_iteration_variables.init_itv_39()
    fortran.define_iteration_variables.init_itv_40()
    fortran.define_iteration_variables.init_itv_41()
    fortran.define_iteration_variables.init_itv_42()

    fortran.define_iteration_variables.init_itv_44()
    fortran.define_iteration_variables.init_itv_45()
    fortran.define_iteration_variables.init_itv_46()
    fortran.define_iteration_variables.init_itv_47()
    fortran.define_iteration_variables.init_itv_48()
    fortran.define_iteration_variables.init_itv_49()
    fortran.define_iteration_variables.init_itv_50()
    fortran.define_iteration_variables.init_itv_51()

    fortran.define_iteration_variables.init_itv_53()
    fortran.define_iteration_variables.init_itv_54()

    fortran.define_iteration_variables.init_itv_56()
    fortran.define_iteration_variables.init_itv_57()
    fortran.define_iteration_variables.init_itv_58()
    fortran.define_iteration_variables.init_itv_59()
    fortran.define_iteration_variables.init_itv_60()
    fortran.define_iteration_variables.init_itv_61()
    fortran.define_iteration_variables.init_itv_62()
    fortran.define_iteration_variables.init_itv_63()
    fortran.define_iteration_variables.init_itv_64()
    fortran.define_iteration_variables.init_itv_65()
    fortran.define_iteration_variables.init_itv_66()
    fortran.define_iteration_variables.init_itv_67()
    fortran.define_iteration_variables.init_itv_68()
    fortran.define_iteration_variables.init_itv_69()
    fortran.define_iteration_variables.init_itv_70()
    fortran.define_iteration_variables.init_itv_71()
    fortran.define_iteration_variables.init_itv_72()
    fortran.define_iteration_variables.init_itv_73()
    fortran.define_iteration_variables.init_itv_74()
    fortran.define_iteration_variables.init_itv_75()

    fortran.define_iteration_variables.init_itv_79()

    fortran.define_iteration_variables.init_itv_81()
    fortran.define_iteration_variables.init_itv_82()
    fortran.define_iteration_variables.init_itv_83()

    fortran.define_iteration_variables.init_itv_85()
    fortran.define_iteration_variables.init_itv_86()

    fortran.define_iteration_variables.init_itv_89()
    fortran.define_iteration_variables.init_itv_90()
    fortran.define_iteration_variables.init_itv_91()
    fortran.define_iteration_variables.init_itv_92()
    fortran.define_iteration_variables.init_itv_93()
    fortran.define_iteration_variables.init_itv_94()
    fortran.define_iteration_variables.init_itv_95()
    fortran.define_iteration_variables.init_itv_96()
    fortran.define_iteration_variables.init_itv_97()
    fortran.define_iteration_variables.init_itv_98()

    fortran.define_iteration_variables.init_itv_103()
    fortran.define_iteration_variables.init_itv_104()
    fortran.define_iteration_variables.init_itv_105()
    fortran.define_iteration_variables.init_itv_106()
    fortran.define_iteration_variables.init_itv_107()
    fortran.define_iteration_variables.init_itv_108()
    fortran.define_iteration_variables.init_itv_109()
    fortran.define_iteration_variables.init_itv_110()
    fortran.define_iteration_variables.init_itv_111()
    fortran.define_iteration_variables.init_itv_112()
    fortran.define_iteration_variables.init_itv_113()
    fortran.define_iteration_variables.init_itv_114()
    fortran.define_iteration_variables.init_itv_115()
    fortran.define_iteration_variables.init_itv_116()
    fortran.define_iteration_variables.init_itv_117()
    fortran.define_iteration_variables.init_itv_118()
    fortran.define_iteration_variables.init_itv_119()
    fortran.define_iteration_variables.init_itv_120()
    fortran.define_iteration_variables.init_itv_121()
    fortran.define_iteration_variables.init_itv_122()
    fortran.define_iteration_variables.init_itv_123()
    fortran.define_iteration_variables.init_itv_124()
    fortran.define_iteration_variables.init_itv_125()
    fortran.define_iteration_variables.init_itv_126()
    fortran.define_iteration_variables.init_itv_127()
    fortran.define_iteration_variables.init_itv_128()
    fortran.define_iteration_variables.init_itv_129()
    fortran.define_iteration_variables.init_itv_130()
    fortran.define_iteration_variables.init_itv_131()
    fortran.define_iteration_variables.init_itv_132()
    fortran.define_iteration_variables.init_itv_133()
    fortran.define_iteration_variables.init_itv_134()
    fortran.define_iteration_variables.init_itv_135()
    fortran.define_iteration_variables.init_itv_136()
    fortran.define_iteration_variables.init_itv_137()
    fortran.define_iteration_variables.init_itv_138()
    fortran.define_iteration_variables.init_itv_139()
    fortran.define_iteration_variables.init_itv_140()
    fortran.define_iteration_variables.init_itv_141()
    fortran.define_iteration_variables.init_itv_142()
    fortran.define_iteration_variables.init_itv_143()
    fortran.define_iteration_variables.init_itv_144()
    fortran.define_iteration_variables.init_itv_145()
    fortran.define_iteration_variables.init_itv_146()
    fortran.define_iteration_variables.init_itv_147()
    fortran.define_iteration_variables.init_itv_148()
    fortran.define_iteration_variables.init_itv_149()
    fortran.define_iteration_variables.init_itv_152()
    fortran.define_iteration_variables.init_itv_153()
    fortran.define_iteration_variables.init_itv_154()
    fortran.define_iteration_variables.init_itv_155()
    fortran.define_iteration_variables.init_itv_156()
    fortran.define_iteration_variables.init_itv_157()
    fortran.define_iteration_variables.init_itv_158()
    fortran.define_iteration_variables.init_itv_159()
    fortran.define_iteration_variables.init_itv_160()
    fortran.define_iteration_variables.init_itv_161()
    fortran.define_iteration_variables.init_itv_162()
    fortran.define_iteration_variables.init_itv_163()
    fortran.define_iteration_variables.init_itv_164()
    fortran.define_iteration_variables.init_itv_165()
    fortran.define_iteration_variables.init_itv_166()
    fortran.define_iteration_variables.init_itv_167()
    fortran.define_iteration_variables.init_itv_168()
    fortran.define_iteration_variables.init_itv_169()
    fortran.define_iteration_variables.init_itv_170()
    fortran.define_iteration_variables.init_itv_171()
    fortran.define_iteration_variables.init_itv_172()
    fortran.define_iteration_variables.init_itv_173()
    fortran.define_iteration_variables.init_itv_174()
    fortran.define_iteration_variables.init_itv_175()
